import { montserrat } from '@/app/ui/fonts'
import '@/app/globals.scss'
import NavBar from '@/app/ui/navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
